packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.117.3'
  - '@supabase/functions-js@2.117.3'
  - '@supabase/postgrest-js@2.117.3'
  - '@supabase/realtime-js@2.117.3'
  - '@supabase/storage-js@2.117.3'
  - '@supabase/supabase-js@2.117.3'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - supabase
  - unrs-resolver
